# This is a basic workflow to help you get started with Actions

name: docs_build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: mk docs and enable stage docs
        run: |
          sed -i -e '/\<docs\>/d' .gitignore
          pwd
          ls -al
          mkdir -p docs
          ls -al
          echo "" > docs/.nojekyll
          #touchã€€docs/.nojekyll
          

      - name: Doxygen Build
        uses: mattnotmitt/doxygen-action@v1.2.1
        with:
          doxyfile-path: Doxyfile
          working-directory: ./
          enable-latex: false
      
      - name: deploy git pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: dev-docs
          publish_dir: . 
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
